### PR TITLE
Non-linear regression

### PR DESCRIPTION
**Pull request by targos**
Included those 4 methods:

potentialRegression
expRegression
polynomialRegression
powerRegression

Not working yet!

@andcastillo please don't push on master, the branch is reserved for working and properly reviewed code. I created this branch (non-linear) with your changes.

### CODE REVIEW

**Comment by andcastillo** [comment]
Sorry

**Comment by maasencioh** [comment]
Is this branch finished?

**Comment by andcastillo** [comment]
No. Still depending on mathjs. I want it using ml-matrix. But I need the aliases for the non-implace methods to be compatible with mathjs. Or to re-write the methos to ml-matrix

**Comment by maasencioh** [comment]
but isn't [this](https://github.com/mljs/matrix/pull/15) new feature in ml-matrix?

**Comment by targos** [comment]
and we need to make the result more user friendly like the simple linear regression as discussed in the meeting.
this PR will not be merged as is, we'll more likely have small ones, one for each regression

**Pull request closed without merging**
